version: 1.0.{build}
image: Visual Studio 2019
build: false
services:
  - postgresql
  - mongodb
  - mysql

environment:
  matrix:
   - python: 311
   - python: 311-x64
   - python: 310
   - python: 310-x64
   - python: 39
   - python: 39-x64

  # postgres
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
  PGUSER: postgres
  PGPASSWORD: Password12!

  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_DATABASE: sqlectron
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  MYSQL_PWD: Password12!
  MONGOPATH: C:/mongodb

init:
  #- "ECHO %PYTHON%"
  #- ps: "ls C:/Python*"
  #- ps: "ls 'C:/Program Files/PostgreSQL'"
  - ps: "ls 'C:/Program Files/MySql'"
  - SET PATH=%MONGOPATH\bin%;%MYSQL_PATH\bin%;%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%

install:
  - python -m pip install wheel"
  - python -m pip install cryptography --only-binary=:all:"
  - python -m pip install -r test_requirements.txt"
  - python -m pip install -r requirements.txt"
  - python -m pip install -e ."

test_script:
  - C:/mongodb/bin/mongo.exe pwmantest tests/init_mongo.js
  - psql -c "CREATE USER tester WITH PASSWORD '123456';"
  - psql -c "create database pwman"
  - psql -c "grant ALL ON DATABASE pwman to tester"
  - mysql -e "create database pwmantest" -uroot
  - mysql -e "create user 'pwman'@'localhost' IDENTIFIED BY '123456'" -uroot
  - mysql -e "grant all on pwmantest.* to 'pwman'@'localhost';" -uroot
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/python.exe setup.py test"

